[package]
name = "sudoku"
version = "0.1.0"
authors = ["Magyari Viktor <viktor.magyari92@gmail.com>"]
edition = "2018"

[dependencies]
serde = {version = "1.0.99", features = ["derive"]}
serde_json = "1.0.40"
